### PR TITLE
Add authorization for better security of routes and user authentication

### PR DESCRIPTION
**Pull request by sherribooher**
Khadijah, not sure if your changes to Sign In, Sign Up, etc. are in this PR...I don't know what has happened with my pulling down not getting the latest changes. Let me know if you can figure out a way for me to fix it on my end. If you need to close this PR too, feel free.

### CODE REVIEW

**Comment by dijahp** [comment]
Hey @sherribooher this one is giving me trouble as well. I may need to revert it. Seeing blank pages on all routes after fixing some compile issues. I was wondering, are your files locally lowercase inside of your components folder? They are lower case in master so when you import as "./SignUp" it cannot find it because the file is "signup.js" or "signup"

**Comment by sherribooher** [comment]
Yes, I went in and fixed them all to (as example) “./SignUp/signup” to get over that. My pages are coming up blank as well. Go ahead and revert everything back to the last working instance and I will figure it all out tomorrow. God, why is this so hard???? I was doing just fine until today.



Regards,

Sherri Booher

**Comment by dijahp** [comment]
Yeah, you def have one of the more difficult responsibilities lol. Okey, reverting!

**Comment by sherribooher** [comment]
I’m seriously thinking about just starting my whole part over so I KNOW that I can get it right.


Regards,

Sherri Booher

**Comment by sherribooher** [comment]
I took the rest of the week off work, so I have the next two days to get it all finished up. I may go ahead and set up the Firebase DB tomorrow just so we have that out of the way and then I can link it up to everything last. At least that way, you guys will have somewhere to store the data and get graphing info if needed.


Regards,

Sherri Booher

**Comment by microagent** [comment]
Great idea!

**Pull request merged**
